# Generated by Django 4.2.4 on 2023-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='like_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
