# Generated by Django 4.2.4 on 2023-08-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_advertisement_like_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
