# Generated by Django 4.2.4 on 2023-08-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_comment_author_alter_emailconfirmation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
